baseURL: "https://fredericbahr.github.io/lernportfolio/"
title: Frederic Bahr -Media Lifecycle Management
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Media Information Lifecycle
  description: "Media Information Lifecycle"
  keywords: [Blog, Portfolio, PaperMod]
  author: "Frederic Bahr"
  DateFormat: "January 2, 2006"
  defaultTheme: "auto" # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"

  label:
    text: "Home"
    icon: /lernportfolio/home.png
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: false

  # home-info mode
  homeInfoParams:
    Title: "Media Lifecycle Management Lernportfolio"
    Content: "Weiter unten finden Sie die einzelnen Beiträge zu den Vorlesungen und Seminaren. \U0001F447"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/fredericbahr/mlm/tree/main/lernportfolio/content"
    Text: "Änderung vorschlagen" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content", "date"]
menu:
  main:
    - identifier: search
      name: Suche
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10
    - identifier: archive
      name: Archiv
      url: /archive/

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
